Repository hms-networks/node-red-contrib-kolibri, pull requests merged in 2020-09, with the labels that each got.

#5 Feature/updates
  LICENSE.txt
  README.md
  lib/connection.js
  lib/consumer.js
  lib/errorcode.js
  lib/jsonrpc.js
  lib/tools.js
  node_modules/ws/LICENSE
  node_modules/ws/README.md
  node_modules/ws/browser.js
  node_modules/ws/index.js
  node_modules/ws/lib/buffer-util.js
  node_modules/ws/lib/constants.js
  node_modules/ws/lib/event-target.js
  node_modules/ws/lib/extension.js
  node_modules/ws/lib/limiter.js
  node_modules/ws/lib/permessage-deflate.js
  node_modules/ws/lib/receiver.js
  node_modules/ws/lib/sender.js
  node_modules/ws/lib/stream.js
  node_modules/ws/lib/validation.js
  node_modules/ws/lib/websocket-server.js
  node_modules/ws/lib/websocket.js
  node_modules/ws/package.json
  nodes/kolibri-broker.html
  nodes/kolibri-broker.js
  nodes/kolibri-in.html
  nodes/kolibri-in.js
  nodes/kolibri-out.html
  nodes/kolibri-out.js
  package-lock.json
  package.json
  test/kolibri_spec.js
Labels: bug, enhancement

#6 remove obsolete node_modules
  node_modules/ws/LICENSE
  node_modules/ws/README.md
  node_modules/ws/browser.js
  node_modules/ws/index.js
  node_modules/ws/lib/buffer-util.js
  node_modules/ws/lib/constants.js
  node_modules/ws/lib/event-target.js
  node_modules/ws/lib/extension.js
  node_modules/ws/lib/limiter.js
  node_modules/ws/lib/permessage-deflate.js
  node_modules/ws/lib/receiver.js
  node_modules/ws/lib/sender.js
  node_modules/ws/lib/stream.js
  node_modules/ws/lib/validation.js
  node_modules/ws/lib/websocket-server.js
  node_modules/ws/lib/websocket.js
  node_modules/ws/package.json
Labels: bug

#4 add proxy support
  LICENSE.txt
  README.md
  lib/connection.js
  lib/consumer.js
  nodes/kolibri-broker.html
  nodes/kolibri-broker.js
  nodes/kolibri-in.html
  nodes/kolibri-in.js
  nodes/kolibri-out.html
  nodes/kolibri-out.js
  package-lock.json
  package.json
  test/kolibri_spec.js
Labels: enhancement

#7 add proxy port validation
  nodes/kolibri-broker.html
Labels: bug
